package Project;

import java.util.Scanner;
import java.util.Random;


public class Driver1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int numDice =3, trials =5;
		int playerPoints =0, computerPoints=0; //counting points
		Random choice = new Random();//It is random obj whose variable is choice. Need this obj to generate random no for my comp.
		Scanner scan = new Scanner(System.in);//input of user choice
		System.out.println("Choose your target number: ");
		int playerTarget = scan.nextInt();
		Game player = new Game(numDice, trials); //game obj. I have constructor where i specify no of dice, no of trials in this game
		playerPoints = player.play("Player",playerTarget);//playerpoint would be returned by play method for game obj. first param:no of player, 2nd param:user input obt by scanner obj.
		int computerTarget = choice.nextInt(9)+1; //1 to 6(nextInt(6): no between 0 to 5)when added 1 become 1 to 6 which is a comp choice
		System.out.println("Computer target is "+ computerTarget);
		Game computer = new Game(numDice, trials); //Computer generate game obj which uses same no of dice and trials. referenace variable to second game obj is called computer;
		computerPoints = computer.play("Computer",computerTarget);//computer reference variable can tell the game obj to play game by passing name of opponent together with target generated by nextInt method coming from random object called choice. and the number pts obt by comp will be stored in comppts primitive.
		if(playerPoints > computerPoints) {
			System.out.println("You win");
		}else if(playerPoints < computerPoints) {
			System.out.println("Computer wins");
		}else {
			System.out.println("Its a Draw. Try it again!!");
		}
		scan.close();//since scanner obj scn is used need to close it
		
		
		
		
				
		

	}

}
